### ISSUE TITLE
Process IceCube neutrino events

### ISSUE THREAD

**Issue by dsteeghs** [GOTO-OBS/goto-alert#35]
The IceCube neutrino events are available publicly using the GCN notice framework:
https://gcn.gsfc.nasa.gov/amon_icecube_gold_bronze_events.html
https://gcn.gsfc.nasa.gov/amon_hese_events.html

These are rare and worth chasing and should be relatively straightforward to add, using a GRB like strategy.

**Comment by martinjohndyer** [comment]
These have been added by @kahoTT in #53.
